title: Golang SDK for CloudEvents
remote_theme: pmarsceill/just-the-docs
plugins:
  - jemoji

aux_links:
  "GitHub Repository":
    - "https://github.com/cloudevents/sdk-go"
  "CloudEvents home":
    - "https://cloudevents.io/"
