version: "2.4"
services:
  jaeger-otel-cloudevents:
    image: jaegertracing/all-in-one:1.25
    environment: 
      - COLLECTOR_ZIPKIN_HOST_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    command: --query.max-clock-skew-adjustment 1s
